[package]
name = "macon"
version = "0.2.0"
edition = "2021"

license = "MIT OR Apache-2.0"
description = "Another builder macro-based generator with its own idioms."
homepage = "https://github.com/loganmzz/macon-rs"
repository = "https://github.com/loganmzz/macon-rs"
readme = "CRATES_IO.md"

keywords = [
    "builder",
    "derive",
    "macro",
    "setter",
]
categories = [
    "rust-patterns",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.38", features = ["extra-traits"] }
