[package]
name = "macon_examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
macon = { path = ".." }
